### PR TITLE
pylint 2.5.1 contains breaking changes. rename do_exit => exit

### PR DESCRIPTION
**Pull request by wangsha**
https://github.com/PyCQA/pylint/blob/master/ChangeLog
What's New in Pylint 2.5.1?
===========================

Release date: 2020-05-05

* Fix a crash in `method-hidden` lookup for unknown base classes

  Close #3527

* Revert pylint.Run's `exit` parameter to ``do_exit``

### CODE REVIEW

**Comment by carsongee** [comment]
Thank you!

**Comment by wangsha** [comment]
Thanks! Appreciate if you can do a release in near future. :)

**Comment by carsongee** [comment]
I'll try and get one out in a few hours

**Comment by gangefors** [comment]
Solves: https://github.com/carsongee/pytest-pylint/issues/133

I'm adding this comment to have it linked to the issue I created.

**Pull request merged**
