### PR TITLE
fix: #120 removing pytest deprecation warning

### PR DESCRIPTION
**Pull request by dineshtrivedi**
Removing PytestDeprecationWarning.

Additional changes:
* Added an explanation of how the plugin works
* Replaced **pytest-pep8** as it hasn't been updated since 2014 and it was blocking class attributes usage.
* Removed **mock** as python 2.7 is not supported any longer

Any feedback is appreciated.
Thank you

### CODE REVIEW

**Comment by dineshtrivedi** [comment]
Refers to #120

**Comment by dineshtrivedi** [comment]
@carsongee 
Could you have a look at it?

**Comment by ShailenNaidoo** [comment]
@dineshtrivedi This is cool, this will help me a lot as we are experiencing the same issue with our codebase.

@carsongee Can you maybe take a look? This will definitely help out a lot :smile:

**Comment by ShailenNaidoo** [comment]
@carsongee Hey man! Just nudging you a bit on this PR :sweat_smile:

**Comment by carsongee** [comment]
😳 I'll review this as soon as I can 🙏

**Pull request closed without merging**
