### PR TITLE
Find .pylintrc in directory of pytest.ini too

### PR DESCRIPTION
**Pull request by andras-tim**
I could not set relative `.pylint.rc` in `pytest.ini` file.

FYI: the **pytest** finds their `pytest.ini`, but it will not set CWD.

### CODE REVIEW

**Comment by carsongee** [comment]
This seems good, can we get a test put in place for this?

**Comment by andras-tim** [comment]
I wrote a test for this ;)

**Comment by carsongee** [comment]
Awesome, thanks for the contribution.  I'll try to put it out in a release in a week or so.

**Comment by andras-tim** [comment]
Thx!

**Pull request merged**
